-- Civ
-- Author: Alex
-- DateCreated: 1/2/2023 3:36:28 PM
--------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------
-- Players
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Players
		(Domain,                            CivilizationType,							Portrait,							PortraitBackground,                         LeaderType,						LeaderName,								LeaderIcon,							LeaderAbilityName,													LeaderAbilityDescription,									LeaderAbilityIcon,					CivilizationName,								CivilizationIcon,							CivilizationAbilityName,									CivilizationAbilityDescription,												CivilizationAbilityIcon)
VALUES	('Players:Expansion2_Players',      'CIVILIZATION_HOLOEN_TENTACULT',			'LEADER_NINOMAE_INANIS.dds',		'LEADER_NINOMAE_INANIS_BACKGROUND',         'LEADER_NINOMAE_INANIS',		'LOC_LEADER_NINOMAE_INANIS_NAME',		'ICON_LEADER_NINOMAE_INANIS',		'LOC_TRAIT_LEADER_NINOMAE_INANIS_ABILITY_NAME',	                    'LOC_TRAIT_LEADER_NINOMAE_INANIS_ABILITY_DESCRIPTION',		'ICON_LEADER_NINOMAE_INANIS',		'LOC_CIVILIZATION_HOLOEN_TENTACULT_NAME',		'ICON_CIVILIZATION_HOLOEN_TENTACULT',		'LOC_TRAIT_CIVILIZATION_HOLOEN_TENTACULT_ABILITY_NAME',		'LOC_TRAIT_CIVILIZATION_HOLOEN_TENTACULT_ABILITY_DESCRIPTION',				'ICON_CIVILIZATION_HOLOEN_TENTACULT');

--------------------------------------------------------------------------------------------------------------------------
-- PlayerItems (e.g. Buildings)
--------------------------------------------------------------------------------------------------------------------------
--INSERT INTO PlayerItems
--		(CivilizationType,						LeaderType,									Type,										Icon,										Name,									  		Description,									SortIndex)
--VALUES	('CIVILIZATION_HOLOEN_TENTACULT',		'LEADER_NINOMAE_INANIS',	'BUILDING_HOLOEN_TENTACULT_QUIET_ROOM',		'ICON_BUILDING_HOLOEN_TENTACULT_QUIET_ROOM',		'LOC_BUILDING_HOLOEN_TENTACULT_QUIET_ROOM',			'LOC_BUILDING_HOLOEN_TENTACULT_QUIET_ROOM',			30);

----------------------------------------------------------------------------------------------------------------------------
-- Types
----------------------------------------------------------------------------------------------------------------------------
INSERT INTO Types
		(Type,								Kind)
VALUES	('CIVILIZATION_HOLOEN_TENTACULT',	'KIND_CIVILIZATION');

----------------------------------------------------------------------------------------------------------------------------
-- Civilizations
----------------------------------------------------------------------------------------------------------------------------
INSERT INTO Civilizations
		(CivilizationType,					Name,										Description,										Adjective,										StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity)
VALUES	('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CIVILIZATION_HOLOEN_TENTACULT_NAME',	'LOC_CIVILIZATION_HOLOEN_TENTACULT_DESCRIPTION',	'LOC_CIVILIZATION_HOLOEN_TENTACULT_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	30,						'ETHNICITY_EURO');

----------------------------------------------------------------------------------------------------------------------------
-- CityNames
----------------------------------------------------------------------------------------------------------------------------
INSERT INTO CityNames
		(CivilizationType,					CityName)
VALUES	('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_1'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_2'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_3'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_4'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_5'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_6'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_7'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_8'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_9'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_10'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_11'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_12'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_13'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_14'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_15'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_16'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_17'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_18'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_19'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_20'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_21'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_22'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_23'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_24'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_25'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_26'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_27'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_28'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_29'),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITY_NAME_HOLOEN_TENTACULT_30');

----------------------------------------------------------------------------------------------------------------------------
-- CivilizationCitizenNames
----------------------------------------------------------------------------------------------------------------------------
INSERT INTO CivilizationCitizenNames
		(CivilizationType,			        CitizenName,								Female,		Modern)
VALUES	('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MALE_1',				0,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MALE_2',				0,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MALE_3',				0,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MALE_4',				0,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MALE_5',				0,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MALE_6',				0,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MALE_7',				0,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MALE_8',				0,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MALE_9',				0,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MALE_10',				0,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_FEMALE_1',			1,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_FEMALE_2',			1,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_FEMALE_3',			1,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_FEMALE_4',			1,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_FEMALE_5',			1,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_FEMALE_6',			1,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_FEMALE_7',			1,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_FEMALE_8',			1,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_FEMALE_9',			1,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_FEMALE_10',			1,			0),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_MALE_1',		0,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_MALE_2',		0,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_MALE_3',		0,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_MALE_4',		0,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_MALE_5',		0,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_MALE_6',		0,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_MALE_7',		0,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_MALE_8',		0,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_MALE_9',		0,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_MALE_10',		0,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_FEMALE_1',		1,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_FEMALE_2',		1,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_FEMALE_3',		1,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_FEMALE_4',		1,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_FEMALE_5',		1,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_FEMALE_6',		1,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_FEMALE_7',		1,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_FEMALE_8',		1,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_FEMALE_9',		1,			1),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CITIZEN_HOLOEN_TENTACULT_MODERN_FEMALE_10',	1,			1);

----------------------------------------------------------------------------------------------------------------------------
-- CivilizationInfo
----------------------------------------------------------------------------------------------------------------------------
INSERT INTO CivilizationInfo
		(CivilizationType,					Header,						Caption,											SortIndex)
VALUES	('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_HOLOEN_TENTACULT_LOCATION',			10),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_HOLOEN_TENTACULT_SIZE',				20),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_HOLOEN_TENTACULT_POPULATION',			30),
		('CIVILIZATION_HOLOEN_TENTACULT',	'LOC_CIVINFO_CAPITAL', 		'LOC_CIVINFO_HOLOEN_TENTACULT_CAPITAL',				40);

----------------------------------------------------------------------------------------------------------------------------
-- CivilizationLeaders
----------------------------------------------------------------------------------------------------------------------------
INSERT INTO CivilizationLeaders
		(CivilizationType,					LeaderType,										CapitalName)
VALUES	('CIVILIZATION_HOLOEN_TENTACULT',	'LEADER_NINOMAE_INANIS',		'LOC_CITY_NAME_HOLOEN_TENTACULT_1');
